### PR TITLE
Make Obama bot cooler than my mom

### PR DESCRIPTION
**Pull request by drutly**

### CODE REVIEW

**Comment by antaxiom** [comment]
Needs more lines, also remove the cock jokes.

**Comment by drutly** [comment]
@antaxiom dude i just found this golden ak in the middle of the desert and then i started doing 90s im so cracked

**Comment by antaxiom** [comment]
Remove mongus.

**Comment by drutly** [comment]
@antaxiom $19 fortnite card

**Comment by antaxiom** [comment]
You missed this `https://tenor.com/view/among-us-among-us-potion-guy-turns-into-among-us-impostor-sus-gif-20349022`

**Comment by drutly** [comment]
@antaxiom POGCHAMP

**Comment by antaxiom** [comment]
PR'ed

**Pull request merged**
